<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261002023628 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE trade (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, proposer_id INT NOT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7E1A4366B13FA634 ON trade (proposer_id)');
        $this->addSql('CREATE INDEX IDX_7E1A4366E92F8F78 ON trade (recipient_id)');
        $this->addSql('CREATE TABLE trade_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, trade_id INT NOT NULL, owner_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7DE052E5C2D9760 ON trade_item (trade_id)');
        $this->addSql('CREATE INDEX IDX_7DE052E57E3C61F9 ON trade_item (owner_id)');
        $this->addSql('CREATE INDEX IDX_7DE052E54ACC9A20 ON trade_item (card_id)');
        $this->addSql('ALTER TABLE trade ADD CONSTRAINT FK_7E1A4366B13FA634 FOREIGN KEY (proposer_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trade ADD CONSTRAINT FK_7E1A4366E92F8F78 FOREIGN KEY (recipient_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trade_item ADD CONSTRAINT FK_7DE052E5C2D9760 FOREIGN KEY (trade_id) REFERENCES trade (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trade_item ADD CONSTRAINT FK_7DE052E57E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trade_item ADD CONSTRAINT FK_7DE052E54ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE trade DROP CONSTRAINT FK_7E1A4366B13FA634');
        $this->addSql('ALTER TABLE trade DROP CONSTRAINT FK_7E1A4366E92F8F78');
        $this->addSql('ALTER TABLE trade_item DROP CONSTRAINT FK_7DE052E5C2D9760');
        $this->addSql('ALTER TABLE trade_item DROP CONSTRAINT FK_7DE052E57E3C61F9');
        $this->addSql('ALTER TABLE trade_item DROP CONSTRAINT FK_7DE052E54ACC9A20');
        $this->addSql('DROP TABLE trade');
        $this->addSql('DROP TABLE trade_item');
    }
}
