<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261006151347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE oauth_identity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(20) NOT NULL, provider_user_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_oauth_provider_user ON oauth_identity (provider, provider_user_id)');
        $this->addSql('CREATE INDEX IDX_4AE96AD8A76ED395 ON oauth_identity (user_id)');
        $this->addSql('ALTER TABLE oauth_identity ADD CONSTRAINT FK_4AE96AD8A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX idx_card_rarity ON card (rarity)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE oauth_identity DROP CONSTRAINT FK_4AE96AD8A76ED395');
        $this->addSql('DROP TABLE oauth_identity');
        $this->addSql('DROP INDEX idx_card_rarity');
    }
}
