<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261004150016 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE login_streak (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, current_day INT NOT NULL, last_claimed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EEEE3CB3A76ED395 ON login_streak (user_id)');
        $this->addSql('ALTER TABLE login_streak ADD CONSTRAINT FK_EEEE3CB3A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE login_streak DROP CONSTRAINT FK_EEEE3CB3A76ED395');
        $this->addSql('DROP TABLE login_streak');
    }
}
