<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001025314 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE shop (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, for_date DATE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC6A4CA2A76ED395 ON shop (user_id)');
        $this->addSql('CREATE TABLE shop_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price INT NOT NULL, sold BOOLEAN NOT NULL, refreshed BOOLEAN NOT NULL, shop_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D7E67EA84D16C4DD ON shop_card (shop_id)');
        $this->addSql('CREATE INDEX IDX_D7E67EA84ACC9A20 ON shop_card (card_id)');
        $this->addSql('ALTER TABLE shop ADD CONSTRAINT FK_AC6A4CA2A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shop_card ADD CONSTRAINT FK_D7E67EA84D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE shop_card ADD CONSTRAINT FK_D7E67EA84ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE shop DROP CONSTRAINT FK_AC6A4CA2A76ED395');
        $this->addSql('ALTER TABLE shop_card DROP CONSTRAINT FK_D7E67EA84D16C4DD');
        $this->addSql('ALTER TABLE shop_card DROP CONSTRAINT FK_D7E67EA84ACC9A20');
        $this->addSql('DROP TABLE shop');
        $this->addSql('DROP TABLE shop_card');
    }
}
