<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261002194312 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE achievement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, trigger VARCHAR(255) NOT NULL, threshold INT DEFAULT NULL, coins_reward INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE card_acquisition_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, acquired_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A5A59673A76ED395 ON card_acquisition_log (user_id)');
        $this->addSql('CREATE INDEX IDX_A5A596734ACC9A20 ON card_acquisition_log (card_id)');
        $this->addSql('CREATE TABLE user_achievement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, unlocked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, achievement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F68B664A76ED395B3EC99FE ON user_achievement (user_id, achievement_id)');
        $this->addSql('CREATE INDEX IDX_3F68B664A76ED395 ON user_achievement (user_id)');
        $this->addSql('CREATE INDEX IDX_3F68B664B3EC99FE ON user_achievement (achievement_id)');
        $this->addSql('ALTER TABLE card_acquisition_log ADD CONSTRAINT FK_A5A59673A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE card_acquisition_log ADD CONSTRAINT FK_A5A596734ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_achievement ADD CONSTRAINT FK_3F68B664A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_achievement ADD CONSTRAINT FK_3F68B664B3EC99FE FOREIGN KEY (achievement_id) REFERENCES achievement (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE card_acquisition_log DROP CONSTRAINT FK_A5A59673A76ED395');
        $this->addSql('ALTER TABLE card_acquisition_log DROP CONSTRAINT FK_A5A596734ACC9A20');
        $this->addSql('ALTER TABLE user_achievement DROP CONSTRAINT FK_3F68B664A76ED395');
        $this->addSql('ALTER TABLE user_achievement DROP CONSTRAINT FK_3F68B664B3EC99FE');
        $this->addSql('DROP TABLE achievement');
        $this->addSql('DROP TABLE card_acquisition_log');
        $this->addSql('DROP TABLE user_achievement');
    }
}
