<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261004014545 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE quest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, description VARCHAR(500) NOT NULL, period VARCHAR(255) NOT NULL, trigger VARCHAR(255) NOT NULL, target INT NOT NULL, coins_reward INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_quest_claim (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, period_key VARCHAR(20) NOT NULL, claimed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, quest_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5DCF8E2EA76ED395209E9EF480C3B793 ON user_quest_claim (user_id, quest_id, period_key)');
        $this->addSql('CREATE INDEX IDX_5DCF8E2EA76ED395 ON user_quest_claim (user_id)');
        $this->addSql('CREATE INDEX IDX_5DCF8E2E209E9EF4 ON user_quest_claim (quest_id)');
        $this->addSql('ALTER TABLE user_quest_claim ADD CONSTRAINT FK_5DCF8E2EA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_quest_claim ADD CONSTRAINT FK_5DCF8E2E209E9EF4 FOREIGN KEY (quest_id) REFERENCES quest (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_quest_claim DROP CONSTRAINT FK_5DCF8E2EA76ED395');
        $this->addSql('ALTER TABLE user_quest_claim DROP CONSTRAINT FK_5DCF8E2E209E9EF4');
        $this->addSql('DROP TABLE quest');
        $this->addSql('DROP TABLE user_quest_claim');
    }
}
