<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003170913 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sale_list_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_sale_list_user_card ON sale_list_item (user_id, card_id)');
        $this->addSql('CREATE INDEX IDX_6CC8C4EDA76ED395 ON sale_list_item (user_id)');
        $this->addSql('CREATE INDEX IDX_6CC8C4ED4ACC9A20 ON sale_list_item (card_id)');
        $this->addSql('CREATE TABLE wishlist_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_wishlist_user_card ON wishlist_item (user_id, card_id)');
        $this->addSql('CREATE INDEX IDX_6424F4E8A76ED395 ON wishlist_item (user_id)');
        $this->addSql('CREATE INDEX IDX_6424F4E84ACC9A20 ON wishlist_item (card_id)');
        $this->addSql('ALTER TABLE sale_list_item ADD CONSTRAINT FK_6CC8C4EDA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_list_item ADD CONSTRAINT FK_6CC8C4ED4ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wishlist_item ADD CONSTRAINT FK_6424F4E8A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wishlist_item ADD CONSTRAINT FK_6424F4E84ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sale_list_item DROP CONSTRAINT FK_6CC8C4EDA76ED395');
        $this->addSql('ALTER TABLE sale_list_item DROP CONSTRAINT FK_6CC8C4ED4ACC9A20');
        $this->addSql('ALTER TABLE wishlist_item DROP CONSTRAINT FK_6424F4E8A76ED395');
        $this->addSql('ALTER TABLE wishlist_item DROP CONSTRAINT FK_6424F4E84ACC9A20');
        $this->addSql('DROP TABLE sale_list_item');
        $this->addSql('DROP TABLE wishlist_item');
    }
}
