<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001193106 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE marketplace_listing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, price INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sold BOOLEAN NOT NULL, cancelled BOOLEAN NOT NULL, seller_id INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2FE69BC88DE820D9 ON marketplace_listing (seller_id)');
        $this->addSql('CREATE INDEX IDX_2FE69BC84ACC9A20 ON marketplace_listing (card_id)');
        $this->addSql('ALTER TABLE marketplace_listing ADD CONSTRAINT FK_2FE69BC88DE820D9 FOREIGN KEY (seller_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE marketplace_listing ADD CONSTRAINT FK_2FE69BC84ACC9A20 FOREIGN KEY (card_id) REFERENCES card (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE marketplace_listing DROP CONSTRAINT FK_2FE69BC88DE820D9');
        $this->addSql('ALTER TABLE marketplace_listing DROP CONSTRAINT FK_2FE69BC84ACC9A20');
        $this->addSql('DROP TABLE marketplace_listing');
    }
}
