<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260928200210 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, actor_id INT NOT NULL, movie_id INT DEFAULT NULL, series_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_937AB03410DAF24A ON character (actor_id)');
        $this->addSql('CREATE INDEX IDX_937AB0348F93B6FC ON character (movie_id)');
        $this->addSql('CREATE INDEX IDX_937AB0345278319C ON character (series_id)');
        $this->addSql('CREATE TABLE movie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT NOT NULL, title VARCHAR(255) NOT NULL, release_date DATE DEFAULT NULL, poster_path VARCHAR(255) DEFAULT NULL, popularity DOUBLE PRECISION DEFAULT NULL, vote_count INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D5EF26F55BCC5E5 ON movie (tmdb_id)');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT NOT NULL, name VARCHAR(255) NOT NULL, profile_path VARCHAR(255) DEFAULT NULL, popularity DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34DCD17655BCC5E5 ON person (tmdb_id)');
        $this->addSql('CREATE TABLE series (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT NOT NULL, name VARCHAR(255) NOT NULL, first_air_date DATE DEFAULT NULL, poster_path VARCHAR(255) DEFAULT NULL, popularity DOUBLE PRECISION DEFAULT NULL, vote_count INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3A10012D55BCC5E5 ON series (tmdb_id)');
        $this->addSql('ALTER TABLE character ADD CONSTRAINT FK_937AB03410DAF24A FOREIGN KEY (actor_id) REFERENCES person (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character ADD CONSTRAINT FK_937AB0348F93B6FC FOREIGN KEY (movie_id) REFERENCES movie (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE character ADD CONSTRAINT FK_937AB0345278319C FOREIGN KEY (series_id) REFERENCES series (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB03410DAF24A');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB0348F93B6FC');
        $this->addSql('ALTER TABLE character DROP CONSTRAINT FK_937AB0345278319C');
        $this->addSql('DROP TABLE character');
        $this->addSql('DROP TABLE movie');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE series');
    }
}
