<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261004143452 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_completed_collection (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, entity_id INT NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B98EB3FAA76ED3958CDE572981257D5D ON user_completed_collection (user_id, type, entity_id)');
        $this->addSql('CREATE INDEX IDX_B98EB3FAA76ED395 ON user_completed_collection (user_id)');
        $this->addSql('ALTER TABLE user_completed_collection ADD CONSTRAINT FK_B98EB3FAA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_completed_collection DROP CONSTRAINT FK_B98EB3FAA76ED395');
        $this->addSql('DROP TABLE user_completed_collection');
    }
}
