<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261010130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Notifications persistées, préférences de notifications et marqueur "stock plein notifié"';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, type VARCHAR(32) NOT NULL, message VARCHAR(255) NOT NULL, link VARCHAR(255) DEFAULT NULL, dedupe_key VARCHAR(100) DEFAULT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_notification_user_created ON notification (user_id, created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_notification_user_dedupe ON notification (user_id, dedupe_key)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('CREATE TABLE notification_preference (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, disabled_types JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_NOTIFICATION_PREF_USER ON notification_preference (user_id)');
        $this->addSql('ALTER TABLE notification_preference ADD CONSTRAINT FK_NOTIFICATION_PREF_USER FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('ALTER TABLE pack_stock ADD full_notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE notification_preference');
        $this->addSql('ALTER TABLE pack_stock DROP full_notified_at');
    }
}
